services:
     app:
       build:
         context: .
       ports:
         - "8000:8000"
       volumes:
         - .:/app
         - /app/.venv
       command:
         [
           "uvicorn",
           "src.main:app",
           "--proxy-headers",
           "--host",
           "0.0.0.0",
           "--port",
           "8000"
         ]